### ISSUE TITLE
Warning: Package LAJuliaUtils does not have Pkg in its dependencies

### ISSUE THREAD

**Issue by cbsteh** [sylvaticus/juliatutorial#13]
I am new to Julia, but I have added before several packages without issues. However, when I attempted to add LAJuliaUtils (my first on an "unregistered" Julia package), I received the following warning message:

` Warning: Package LAJuliaUtils does not have Pkg in its dependencies:
│ - If you have LAJuliaUtils checked out for development and have
│   added Pkg as a dependency but haven't updated your primary
│   environment's manifest file, try Pkg.resolve().
`
I have tried `Pkg.resolve()` but this warning message persists. 

P.S. I am using vscode.

**Comment by sylvaticus** [comment]
thank you, I'll have a look...

**Comment by sylvaticus** [comment]
Thank you this should have been sorted in the LAJuliaUtils (the package "Pkg" - a standard lib package used somewhere in the library - was not declared in the list of dependencies of the library).

you can update the latest version by issuing `] up` on your Julia prompt.

**Comment by cbsteh** [comment]
Yes, it now works. Thanks for working on this so quickly! 👍
